### ISSUE TITLE
Generar estructura projecte

### ISSUE THREAD

**Issue by dmoralesl** [DanielEspanadero/nodeInitialDemo#1]
Creació de les carpetes i fitxers necessaris per a treballar. Únicament estructura amb la nomenclatura correcta, sense contingut en cap cas.
Aquesta tasca bloquejarà la resta de tasques.
Una idea a nivell d'arquitectura seria la següent:

- /src
  - app.js
  - /models
  - /services
  - /repositories

El fitxer app.js serà l'entry point de l'aplicació i on es generarà també la part d'interacció amb l'usuari per consola.
A la carpeta models guardarem la materialització de les entitats de la base de dades.
A services tindrem la lògica de negoci per fer les operacions de creació, lectura, eliminació... de les tasques.
A la carpeta repositories tindrem la capa d'abstracció per manipular la BBDD.

**Comment by DanielEspanadero** [comment]
He afegit la carpeta helpers per integrar la lògica de la interacció i deixar l'app.js tan net com sigui possible. Si ha d'anar a altre costat el canviem sense problema, no sabia on encaixar-lo 😅.

**Comment by DanielEspanadero** [comment]
He creat la carpeta db per desar (per ara) el fitxer data.json.
