### ISSUE TITLE
Interacció amb l'usuari

### ISSUE THREAD

**Issue by dmoralesl** [DanielEspanadero/nodeInitialDemo#2]
Oferir a l'usuari per consola les opcions de: crear tasca, actualitzar tasca, esborrar tasca, llistar totes les tasques o llistar una tasca específica.

S'haurà de fer ús dels servicis creats a la carpeta /services i el codi d'interacció s'ubicarà al fitxer app.js

**Comment by DanielEspanadero** [comment]
D'aquesta part estan fetes **_la interfície gràfica, pausar la consola quan se selecciona una opció i la lectura d'inputs_**. Faltaran **_la llista de tasques per esborrar, confirmació abans d'esborrar una tasca i checklist de tasques completes/incompletes_** que ho faré quan estigui feta la part del servei de tasques per fer la integració.

Deixo per [aquí](https://www.npmjs.com/package/inquirer) la documentació d'inquirer per si voleu fer una ullada.
