### ISSUE TITLE
Crear model de Tasca

### ISSUE THREAD

**Issue by dmoralesl** [DanielEspanadero/nodeInitialDemo#4]
S'haurà de materialitzar l'objecte Tasca en una classe que es pugui fer servir de model en qualsevol ORM de base de dades que utilitzem.

El codi estarà ubicat a un fitxer anomenat TaskModel.js a la carpeta /models i la classe tindrà per nom Task.

(caldrà veure si es una classe o un objecte amb X claus: valor)

**Comment by DanielEspanadero** [comment]
Task model fet! 
Ho deixo pendent de revisió per si veieu que cal afegir alguna cosa més o que no és correcte, però crec que amb això @dmoralesl  ja pots treballar a l'hora de crear serveis de tasques.
El tema del gitflow no sé si ho estem fent correctament, al git graph les branques estan quedant una mica estranyes (És possible que sigui la meva configuració) i al fer el merge, la branca des de la qual he fet el merge no s'ha esborrat , no sé si això és correcte.
Treient això, tot va sobre rodes. 😁👍🏻
